import { Caption, AIResponse } from '../types';

// Mock AI service - in production, you'd use OpenAI API or similar
export const generateAIResponse = async (
  captions: Caption[],
  type: 'summary' | 'expand' | 'outline' | 'custom',
  customPrompt?: string
): Promise<AIResponse> => {
  // Simulate API delay
  await new Promise(resolve => setTimeout(resolve, 1500 + Math.random() * 2000));

  const fullTranscript = captions.map(c => c.originalText).join(' ');
  
  let content = '';
  
  switch (type) {
    case 'summary':
      content = `# Summary\n\nThis conversation covered the following key points:\n\n- Main topic discussed: ${fullTranscript.slice(0, 50)}...\n- Key insights shared\n- Important decisions made\n\n*This is a mock summary. In production, this would be generated by AI based on the full transcript.*`;
      break;
      
    case 'expand':
      content = `# Expanded Analysis\n\n## Context\nThe conversation began with discussions about ${fullTranscript.slice(0, 30)}...\n\n## Detailed Breakdown\n1. **Opening remarks**: The speaker introduced the topic\n2. **Main discussion**: Key points were elaborated\n3. **Conclusions**: Final thoughts were shared\n\n## Implications\nThis discussion suggests several important considerations for future planning.\n\n*This is a mock expansion. In production, this would provide detailed analysis of the transcript.*`;
      break;
      
    case 'outline':
      content = `# Conversation Outline\n\n## I. Introduction\n   A. Opening statements\n   B. Context setting\n\n## II. Main Discussion\n   A. Primary topics\n      1. ${fullTranscript.slice(0, 20)}...\n      2. Related points\n   B. Supporting details\n\n## III. Conclusion\n   A. Summary of key points\n   B. Next steps\n\n*This is a mock outline. In production, this would be structured based on the actual content.*`;
      break;
      
    case 'custom':
      content = `# Custom AI Response\n\n**Your question**: ${customPrompt}\n\n**Analysis**: Based on the transcript provided, here are some insights:\n\n${fullTranscript.slice(0, 100)}...\n\nThe conversation touches on several interesting points that relate to your question. Here's what I found most relevant:\n\n- Key insight 1\n- Key insight 2\n- Key insight 3\n\n*This is a mock response. In production, this would be a custom AI analysis based on your specific question.*`;
      break;
  }

  return {
    type,
    content,
    timestamp: new Date()
  };
};